# Generated by Django 3.0.3 on 2020-03-01 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
